# Generated by Django 5.0.3 on 2024-03-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=15)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
